book slider
FRONT-ON/bookilist pull request #4
Opened 2023-06-19 10:06 UTC by framika

Функционал Book slider в соответствии с задачей [Book slider Task](https://www.notion.so/book-slider-5035ed47baf44590959865ab08c9a22e), а именно: 
- сформировала моковые данные книг (название, автор сокращенный, автор полный, обложка, статус для фильтрации);
- создала компонент Book для отрисовки книги;
- создала компонент Carousel для отрисовки карусели с использованием библиотеки [swiper](https://swiperjs.com/swiper-api);
- создала компонент BookCarousel для отрисовки карусели с книгами;
- добавила в корневой компонент Home вывод компонента BookCarousel для бестселлеров и новых книг.

2023-06-23 20:57 UTC, FRONT-ON requested changes

2023-06-23 20:57 UTC, FRONT-ON commented on package.json
> +    "swiper": "^9.4.1"
Давайте будем использовать фиксированные версии зависимостей, для этого нужно указывать зависимости без ^. Для того, чтобы при закачивании зависимостей они закачивались без ^, нужно использовать флаг --save-exact.

2023-06-23 20:57 UTC, FRONT-ON commented on src/assets/img/arrows/arrowAfter.svg
Предлагаю не добавлять в проект 2 одинаковые картинки, отличие которых только в градусе их поворота. Предлагаю добавлять 1 картинку, которую переворачивать с помощью css

2023-06-23 20:57 UTC, FRONT-ON commented on src/mock/booksMock.tsx
> +export interface BookType {
Можно наверное просто Book

2023-06-23 20:57 UTC, FRONT-ON commented on src/pages/Home/BookCarousel/BookCarousel.tsx
> +	borderRadius: '15px',
Можно просто 15

2023-06-23 20:57 UTC, FRONT-ON commented on src/pages/Home/BookCarousel/BookCarousel.tsx
> +		fontSize: '21px',
Можно просто число

2023-06-23 20:57 UTC, FRONT-ON commented on src/pages/Home/BookCarousel/BookCarousel.tsx
> +		fontSize: '21px',
И в других местах тоже

2023-06-23 20:57 UTC, FRONT-ON commented on src/pages/Home/Home.tsx
> +	// top: '40%',
Комментарий можно убрать

2023-06-23 20:57 UTC, FRONT-ON commented on src/pages/Home/Home.tsx
> +				<BookCarousel filter={'books'} text={'Bestsellers'} />
Можно наверное просто filter="books" text="Bestsellers"

2023-06-23 20:57 UTC, FRONT-ON commented on src/shared/atoms/Container.tsx
> +export const Container = ({ children, padding }: Props) => {
Предлагаю переписать компонент:
Сделать так чтобы он принимал все то, что принимает компонент Container из mui. Для этого нужно удалить интерфейс Props, импортировать из mui тип ContainerProps и типизировать компонент с помощью него.
После этого можно будет не передавать пропс padding, а делать в месте использования styled-компонент на основе этого, при необходимости указывая уникальные стили. В таком случае в компонент Container будет прокидываться сгенерированный className, который включен в состав пропсов ContainerProps

2023-06-23 20:57 UTC, FRONT-ON commented on src/shared/molecules/Book.tsx
> +	// filter: 'drop-shadow(0px 4px 4px rgba(0, 0, 0, 0.25))',
Можно удалить комментарий

2023-06-23 20:57 UTC, FRONT-ON commented on src/shared/organisms/Carousel.tsx
> +			navigationPrevRef.current?.addEventListener('click', () => {
Почему через addEventListener? Почему не onClick на Arrow?

2023-06-23 20:57 UTC, FRONT-ON commented on src/shared/organisms/Carousel.tsx
> +	const loopedBooks = [...books, ...books, ...books];
Выглядит, как костыль. Почему не сделать так, чтобы это реально было зациклено? Чтобы после последней книги из списка бралась снова первая?

2023-06-23 20:57 UTC, FRONT-ON commented on src/shared/organisms/Carousel.tsx
> +				// centeredSlides={true}
Можно убрать комментарий

2023-06-23 20:57 UTC, FRONT-ON commented on src/shared/organisms/Carousel.tsx
> +	const loopedBooks = [...books, ...books, ...books];
Или я не совсем поняла, для чего это нужно

2023-06-24 12:19 UTC, framika commented on src/pages/Home/BookCarousel/BookCarousel.tsx
> +	borderRadius: '15px',
почему то он не воспринимает без конкретного указания единиц измерения

2023-06-24 13:22 UTC, framika commented on src/shared/organisms/Carousel.tsx
> +	const loopedBooks = [...books, ...books, ...books];
реально запихнула чисто как костыль
получилось исправить корректно применив loop из switch (надо было добавить количество моковых книг (для карусели всегда должно быть >=8)

2023-06-30 08:16 UTC, FRONT-ON requested changes

2023-06-30 08:16 UTC, FRONT-ON commented on src/pages/Home/Home.tsx
> -import { Box as MuiBox, Typography as MuiTypography, styled } from '@mui/material';
Такое ощущение, что слетела настройка prettier. Раньше было отформатировано правильно.

2023-06-30 08:16 UTC, FRONT-ON commented on src/shared/atoms/Container.tsx
> +    '&.carouselContainer': {
Тут не должно быть стилей, не относящихся конкретно к компоненту Container. Нужно в месте использования создать на основе компонента Container styled-компонент. Тогда в прописанный и переданный компоненту AdoptedContainer className автоматически передастся нужный стиль. Компонент Container - общий, переиспользуемый, он не должен содержать в себе стили, не относящиеся к конкретно данному компоненту.

2023-06-30 08:16 UTC, FRONT-ON commented on src/shared/organisms/Carousel.tsx
> +			navigationPrevRef.current.onclick = () => {
Этот момент хотелось бы обсудить на встрече

2023-07-21 15:05 UTC, AVirronen approved these changes

2023-08-06 10:57 UTC, Downypaw approved these changes

2023-08-06 11:04 UTC, FRONT-ON approved these changes

2023-08-06 11:04 UTC, FRONT-ON commented on src/assets/img/background2.png
А для чего нужен background2?

2023-08-06 11:04 UTC, FRONT-ON commented on src/pages/Home/BookCarousel/BookCarousel.tsx
> +	fontWeight: '500',
Можно также тут просто цифру указывать

2023-08-06 11:04 UTC, merged