Navigation
FRONT-ON/bookilist pull request #5
Opened 2023-07-25 11:02 UTC by framika

В соответствии с задачей [Navigation](https://www.notion.so/Navigation-e1e06adc272345e4838a043631a22f21)
- создала компонент ArrowUp для стрелки наверх на странице и использовала его в Portal.tsx
- сделала более корректное отображение фона + картинки
- создала общий компонент src\shared\atoms\Arrow.tsx для использования стрелок

2023-08-06 13:53 UTC, FRONT-ON requested changes

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +	top: 'calc(100vh - 149px)',
А почему не bottom: 149? Вроде бы может так сработать и будет короче. Эта запись говорит, отступить от низа родителя на 149 пикселей.

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +		top: 'calc(100vh - 138px)',
тут тоже можно попробовать через bottom

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +		top: 'calc(100vh - 130px)',
и тут

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +export const ArrowUp = memo(() => {
Можно еще посмотреть, насколько здесь нужно использовать memo: посмотреть сколько раз компонент рендерится без мемо и сколько с ним. Кажется, что здесь memo может быть не нужно и не помогает сократить количество ререндеров. При этом использование мемоизации небесплатно с точки зрения производительности. При использовании memo происходит сравнение пропсов - операция достаточно быстрая и оптимизированная в React, но все еще небесплатная.

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +import * as React from 'react';
Импорт реакта не нужен в react 18

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +		const scrollAmount = 200;
Немного не понимаю, почему scrollAmount какое-то статичное значение 200? Это же значение наверное может различаться в зависимости от разрешения экрана конкретного пользователя?

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +		const scrollCurrent = window.scrollY || document.documentElement.scrollTop;
Почему либо это значение, либо это?

2023-08-06 13:53 UTC, FRONT-ON commented on src/shared/atoms/Arrow.tsx
> +import * as React from 'react';
Импорт реакта не нужен в react 18

2023-08-06 13:53 UTC, FRONT-ON commented on src/shared/atoms/Arrow.tsx
> +import arrowCarousel from '@assets/img/arrowDefault.svg';
Теперь эта стрелка используется не только для карусели. Может стоит переименовать ее в просто arrow?

2023-08-06 13:53 UTC, FRONT-ON commented on src/shared/atoms/Arrow.tsx
> +Arrow.displayName = 'Arrow';
Тут эта строчка не нужна, так как компонент не обернут в memo. Мы прописываем displayName только для компонентов обернутых в memo с целью облегчения отладки. memo возвращает новый компонент, который является анонимным. Если не прописывать displayName для него, то в React Devtools этот компонент будет отображаться анонимным, без имени - Anonymous

2023-08-06 13:53 UTC, FRONT-ON commented on src/harness/portal/Portal.tsx
>  export const Portal = memo(({ children }: Props) => {
Возможно здесь  memo также не нужно использовать.

2023-08-06 13:53 UTC, FRONT-ON commented on src/shared/organisms/Carousel.tsx
> +			<Arrow text={'ArrowPrev'} onClick={() => swiperOnClick('Prev')} rotate={0} style={{ padding: '0 3.5% 0 0' }} />
можно пропс текст без скобочек указывать text="text"

2023-08-06 13:53 UTC, FRONT-ON commented on src/shared/organisms/Carousel.tsx
> +				wrappercomponent={WrapperComponent}>
Лучше оставить wrapperComponent, а не слепливать слова друг с другом

2023-08-09 16:23 UTC, framika commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +export const ArrowUp = memo(() => {
ты права! компонент ререндерится с memo столько же раз сколько и без него

2023-08-09 16:25 UTC, framika commented on src/shared/organisms/Carousel.tsx
> +				wrappercomponent={WrapperComponent}>
wrapperComponent вроде можно убрать, по факту он ни на что больше не влияет

2023-09-27 11:39 UTC, framika commented on src/harness/portal/Portal.tsx
>  export const Portal = memo(({ children }: Props) => {
а вроде изменения во втором коммите по этому есть (в navigation 2.0)

2023-09-27 11:46 UTC, framika commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +		const scrollAmount = 200;
ой, кажется случайно пропустила!! 
сейчас изменю на let, WS правда на это ругается пока без изменения значения

2023-10-16 15:17 UTC, FRONT-ON approved these changes

2023-10-16 15:17 UTC, FRONT-ON commented on src/harness/portal/ArrowUp/ArrowUp.tsx
> +		let scrollAmount = 200;
Зачем?

2023-10-17 12:19 UTC, AVirronen approved these changes
Everythings is fine

2023-10-23 16:11 UTC, merged